"""EDLファイル生成モジュール"""

from typing import List, Dict, Any
import os

class EDLGenerator:
    def __init__(self):
        pass

    def generate(self, scenes: List[Dict[str, Any]], output_path: str) -> None:
        """EDLファイルを生成"""
        # 出力ディレクトリの作成
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        # EDLファイルの生成
        edl_lines = []
        
        # ヘッダー
        edl_lines.append("TITLE: Generated by Video Edit Agent")
        edl_lines.append("FCM: NON-DROP FRAME")
        edl_lines.append("")  # 空行
        
        # シーンの処理
        for i, scene in enumerate(scenes, 1):
            try:
                # タイムコードの変換
                start_tc = self._seconds_to_timecode(scene['start_time'])
                end_tc = self._seconds_to_timecode(scene['end_time'])
                
                # EDLエントリの作成
                entry = self._create_edl_entry(
                    i, scene['content_id'], start_tc, end_tc,
                    scene.get('transcript', ''), scene.get('effects', [])
                )
                edl_lines.append(entry)
            except Exception as e:
                print(f"警告: シーン {i} の処理中にエラーが発生しました: {str(e)}")
                continue
        
        # ファイルの書き込み
        with open(output_path, 'w', encoding='utf-8-sig', newline='\n') as f:
            f.write('\n'.join(edl_lines))

    def _create_edl_entry(self, index: int, clip_name: str,
                         start_tc: str, end_tc: str,
                         transcript: str, effects: List[str]) -> str:
        """EDLエントリを生成"""
        # エントリの基本構造
        entry = [
            f"{index:03d}  {index:03d}     V     C        ",
            f"{start_tc} {end_tc} {start_tc} {end_tc}"
        ]
        
        # クリップ名とトランスクリプト
        entry.append(f"* FROM CLIP NAME: {clip_name}")
        if transcript:
            entry.append(f"* {transcript}")
        
        # エフェクト情報
        if effects:
            entry.append(f"* EFFECTS: {', '.join(effects)}")
        
        return '\n'.join(entry)

    def _seconds_to_timecode(self, seconds: float) -> str:
        """秒数をタイムコード形式に変換"""
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        seconds = int(seconds % 60)
        frames = int((seconds % 1) * 30)  # 30fpsを想定
        
        return f"{hours:02d}:{minutes:02d}:{seconds:02d}:{frames:02d}"
